name: linting, testing, building
on:
  push:
    branches:
      - '*'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: Checkout repository
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci